### ISSUE TITLE
Not h5p data to Import/Export after installation

### ISSUE THREAD

**Issue by jpenhos** [dthies/moodle-qformat_h5p#1]
Hello, I followed all installation instructions and after having the plugin installed the is no reference to h5p in import/export questions:

![image](https://user-images.githubusercontent.com/64661151/84219134-718aeb00-aa95-11ea-92b9-6f60faf1a6da.png)

**Comment by dthies** [comment]
Did you log out and log in again as admin and go through the plugin installation? It looks to be like system upgrade step has not happened

**Comment by jpenhos** [comment]
Hey thanks for your response

Yes.. I did it and several times tried!

José Penhos

El 11 jun 2020, a la(s) 6:42, Daniel Thies <notifications@github.com> escribió:

﻿

Did you log out and log in again as admin and go through the plugin installation? It looks to be like system upgrade step has not happened

**Comment by dthies** [comment]
Can you try to uninstall and reinstall of the plugin? It may have had an error when it installed and not be complete.

**Comment by jpenhos** [comment]
Hey Daniel

Did it again, no change

I even tried by cloning and by zip

Any idea?

José Penhos

El 11 jun 2020, a la(s) 10:46, Daniel Thies <notifications@github.com> escribió:

﻿

Can you try to uninstall and reinstall of the plugin? It may have had an error when it installed and not be complete.

**Comment by dthies** [comment]
José, 

I am sorry I did not mean remove or change the files, but to uninstall in the Moodle admin settings. On the screenshot above click "Deinstalar". You will confirm, you want to uninstall. After that is should ask to install again. Watch for errors.

**Comment by jpenhos** [comment]
Hey again!

These are the errors I get:

Warning: include(/var/www/moodle-default/moodle/question/format/h5p/version.php): failed to open stream: No such file or directory in /var/www/moodle-default/moodle/lib/classes/component.php on line 1138

Warning: include(): Failed opening '/var/www/moodle-default/moodle/question/format/h5p/version.php' for inclusion (include_path='/var/www/moodle-default/moodle/lib/pear:.:/usr/share/php') in /var/www/moodle-default/moodle/lib/classes/component.php on line 1138

Warning: include(/var/www/moodle-default/moodle/question/format/h5p/version.php): failed to open stream: No such file or directory in /var/www/moodle-default/moodle/lib/classes/plugin_manager.php on line 305

Warning: include(): Failed opening '/var/www/moodle-default/moodle/question/format/h5p/version.php' for inclusion (include_path='/var/www/moodle-default/moodle/lib/pear:.:/usr/share/php') in /var/www/moodle-default/moodle/lib/classes/plugin_manager.php on line 305
Plugin qformat_h5p does not declare valid $plugin->component in its version.php.

  *   line 315 of /lib/classes/plugin_manager.php: call to debugging()
  *   line 335 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
  *   line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
  *   line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
  *   line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
  *   line 395 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
  *   line 355 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
  *   line 745 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
  *   line 702 of /admin/index.php: call to core_plugin_manager->all_plugins_ok()



Jose Penhos
jpenhos@hotmail.com
________________________________

**Comment by dthies** [comment]
Hi Jose,
That looks like is is a file permission error on the files that you have installed. The default permissions allows the file owner to read the file, but not the web server user (usually apache, nginx or www-data depending or distribution). You need to add read permission for all users.

**Comment by jpenhos** [comment]
Hi again!

Permission issue already solved, but still have this error:

Warning: include(): Failed opening '/var/www/moodle-default/moodle/question/format/h5p/version.php' for inclusion (include_path='/var/www/moodle-default/moodle/lib/pear:.:/usr/share/php') in /var/www/moodle-default/moodle/lib/classes/plugin_manager.php on line 305
Plugin qformat_h5p does not declare valid $plugin->component in its version.php.

  *   line 315 of /lib/classes/plugin_manager.php: call to debugging()
  *   line 335 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
  *   line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
  *   line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
  *   line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
  *   line 395 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
  *   line 72 of /admin/settings/messaging.php: call to core_plugin_manager->get_plugins_of_type()
  *   line 8383 of /lib/adminlib.php: call to require()
  *   line 19 of /admin/settings.php: call to admin_get_root()

________________________________

**Comment by dthies** [comment]
The warning indicates it is still not able to read version.php. You may have fixed permission on directory, but not all the files.

**Comment by jpenhos** [comment]
Hey!

Done!!
the problem was not having all files in the h5p directory but in h5p/*/

Regards

________________________________
